[package]
name = "rustpbx"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A SIP PBX implementation in Rust"
license = "MIT"
repository = "https://github.com/restsend/rustpbx"
readme = "README.md"
keywords = ["sip", "voip", "telephony", "pbx"]
categories = ["network-programming", "multimedia"]


[dependencies]
anyhow = "1.0"
async-trait = "0.1"
bytes = "1.5"
futures = "0.3"
nnnoiseless = { version = "0.5", features = ["default"] }
rubato = "0.16.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
tokio-tungstenite = { version = "0.26.2", features = ["rustls"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
url = "2.5"
uuid = { version = "1.7", features = ["v4"] }
webrtc-vad = "0.4"
parking_lot = "0.12"
clap = { version = "4.5", features = ["derive"] }
toml = "0.8"
rand = "0.8"
hound = "3.5.1"
rtp-rs = "0.6.0"

[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"
