[package]
name = "rustpbx"
version = "0.1.0"
edition = "2021"
authors = ["Your Name <your.email@example.com>"]
description = "A SIP PBX implementation in Rust"
license = "MIT"
repository = "https://github.com/restsend/rustpbx"
readme = "README.md"
keywords = ["sip", "voip", "telephony", "pbx"]
categories = ["network-programming", "multimedia"]


[dependencies]
anyhow = "1.0"
async-trait = "0.1"
axum = { version = "0.8.1", features = ["ws"] }
tower-http = { version = "0.6.2", features = ["fs", "cors"] }
bytes = "1.5"
futures = "0.3"
nnnoiseless = { version = "0.5", features = ["default"] }
rubato = "0.16.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.36", features = ["full"] }
tokio-stream = "0.1"
tokio-tungstenite = { version = "0.26.2", features = ["rustls"] }
tokio-util = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
url = "2.5"
uuid = { version = "1.7", features = ["v4"] }
webrtc = "0.12.0"
webrtc-vad = "0.4.0"
clap = { version = "4.5", features = ["derive"] }
toml = "0.8"
rand = "0.9.0"
hound = "3.5.1"
rtp-rs = "0.6.0"
voice_activity_detector = "0.2.0"
chrono = "0.4.40"
rsipstack = "0.1.4"
rsip = "0.4.0"
reqwest = { version = "0.11", features = ["json"] }
base64 = "0.21"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
dotenv = "0.15"
async-openai = "0.28.0"
md5 = "0.7.0"
once_cell = "1.19.0"
cpal = "0.15.2"

[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"
mockall = "0.11"

[[example]]
name = "webrtc-demo"
path = "examples/webrtc-demo/src/main.rs"

[[example]]
name = "llm-example"
path = "examples/llm_example.rs"

[[example]]
name = "webrtc-call"
path = "examples/webrtc-call/src/main.rs"

[[example]]
name = "audio-agent"
path = "examples/audio_agent.rs"
