[package]
name = "rustpbx"
version = "0.2.3"
edition = "2021"
authors = ["jinti<shenjindi@fourz.cn>"]
description = "A SIP PBX implementation in Rust"
license = "MIT"
repository = "https://github.com/restsend/rustpbx"
readme = "README.md"
keywords = ["sip", "voip", "telephony", "pbx", "webrtc"]
categories = ["network-programming", "multimedia"]

[features]
vad_webrtc = ["webrtc-vad"]
vad_silero = ["voice_activity_detector"]
default = ["vad_webrtc", "vad_silero"]
not_vad = []

[dependencies]
anyhow = "1.0.98"
async-trait = "0.1.88"
axum = { version = "0.8.3", features = ["ws", "tokio"] }
tower-http = { version = "0.6.2", features = ["fs", "cors"] }
bytes = "1.10.1"
futures = "0.3.31"
nnnoiseless = { version = "0.5", features = ["default"] }
rubato = "0.16.2"
rustls = { version = "0.23.26", features = ["ring"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.17"
tokio-tungstenite = { version = "0.26.2", features = [
    "rustls-tls-native-roots",
] }
tokio-util = "0.7.15"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-appender = "0.2"
url = "2.5.4"
uuid = { version = "1.16.0", features = ["v4"] }
webrtc = "0.12.0"
webrtc-vad = { version = "0.4.0", optional = true }
clap = { version = "4.5", features = ["derive"] }
toml = "0.8"
rand = "0.9.0"
hound = "3.5.1"
voice_activity_detector = { version = "0.2.0", optional = true }
chrono = "0.4.40"
rsipstack = "0.1.7"
rsip = "0.4.0"
reqwest = { version = "0.12.15", features = ["json", "rustls-tls"] }
base64 = "0.22.1"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4.3"
dotenv = "0.15"
async-openai = "0.28.1"
md5 = "0.7.0"
once_cell = "1.21.3"
cpal = "0.15.3"
regex = "1.11.1"
ring = "0.17.14"
http = "1.3.1"
urlencoding = "2.1.3"
byteorder = "1.5.0"
get_if_addrs = "0.5.3"
symphonia = { version = "0.5.4", features = ["mp3"] }
tempfile = "3.8"
rmp3 = "0.3"


[dev-dependencies]
tempfile = "3.8"
tokio-test = "0.4"
mockall = "0.13.1"

[[example]]
name = "webrtc-demo"
path = "examples/webrtc-demo/src/main.rs"


[[example]]
name = "voice-demo"
path = "examples/voice_demo.rs"
